package com.tally.core

/**
 * The icon a new category's name suggests: "Coffee" takes the cup, "Épicerie" the cart, "Loyer"
 * the house. Words are matched at the start of a word of the name, in English and French, so the
 * owner can still pick any other glyph. Every key returned is one of [Defaults.iconKeys].
 */
object IconHints {

    private val HINTS: List<Pair<String, List<String>>> = listOf(
        // Before the food words, so "Dog food" is the paw and not the knife and fork.
        "pets" to listOf("pet", "dog", "chien", "cat ", "chat ", "veterinar", "animal"),
        "coffee" to listOf("coffee", "cafe", "espresso"),
        "tea" to listOf("tea", "the "),
        "pizza" to listOf("pizza"),
        "fastfood" to listOf("fast food", "takeout", "take out", "delivery food", "livraison"),
        "lunch" to listOf("lunch", "dinner", "diner", "souper", "burger"),
        "bakery" to listOf("bakery", "boulangerie", "patisserie", "pastry"),
        "beer" to listOf("beer", "biere"),
        "wine" to listOf("wine", "vin "),
        "liquor" to listOf("alcohol", "alcool", "liquor", "saq"),
        "bar" to listOf("bar ", "bars", "drinks", "cocktail"),
        "dining" to listOf("dining", "restaurant", "resto", "food", "bouffe", "eating out"),
        "cart" to listOf("grocer", "epicerie", "supermarket", "marche"),
        "fuel" to listOf("gas", "fuel", "essence"),
        "parking" to listOf("parking", "stationnement"),
        "ev" to listOf("charging", "recharge"),
        "carrepair" to listOf("car repair", "mechanic", "garage", "entretien auto"),
        "car" to listOf("car", "auto", "voiture", "vehicle"),
        "taxi" to listOf("taxi", "uber", "lyft", "rides"),
        "bike" to listOf("bike", "velo", "bixi"),
        "train" to listOf("train", "via rail"),
        "subway" to listOf("metro", "subway"),
        "transport" to listOf("transport", "transit", "bus", "commute"),
        "flight" to listOf("flight", "vol ", "vols", "avion", "airline"),
        "hotel" to listOf("hotel", "lodging", "hebergement"),
        "luggage" to listOf("travel", "voyage", "vacation", "vacances", "trip"),
        "home" to listOf("rent", "loyer", "housing", "logement", "mortgage", "hypotheque"),
        "apartment" to listOf("condo", "apartment", "appartement"),
        "bolt" to listOf("electric", "hydro", "electricite", "power", "utilities"),
        "water" to listOf("water", "eau"),
        "heat" to listOf("heating", "chauffage"),
        "phone" to listOf("phone", "cell", "mobile", "telephone"),
        "wifi" to listOf("internet", "wifi"),
        "tv" to listOf("tv", "television", "cable"),
        "insurance" to listOf("insurance", "assurance"),
        "furniture" to listOf("furniture", "meuble"),
        "repairs" to listOf("repair", "reparation", "renovation", "tools", "outils"),
        "cleaning" to listOf("cleaning", "menage", "nettoyage"),
        "laundry" to listOf("laundry", "lavage"),
        "garden" to listOf("garden", "jardin", "lawn"),
        "clothes" to listOf("clothes", "clothing", "vetement", "apparel", "linge"),
        "computer" to listOf("computer", "ordinateur", "tech", "electronic", "electronique"),
        "headphones" to listOf("audio", "headphone"),
        "toys" to listOf("toy", "jouet"),
        "flowers" to listOf("flower", "fleur", "plants", "plantes"),
        "jewelry" to listOf("jewel", "bijou"),
        "bag" to listOf("shopping", "magasinage", "achats"),
        "medication" to listOf("medication", "medicament", "prescription"),
        "pharmacy" to listOf("pharmac"),
        "hospital" to listOf("hospital", "hopital"),
        "medical" to listOf("medical", "doctor", "medecin", "dentist", "dentiste", "clinic", "clinique"),
        "eyes" to listOf("glasses", "lunettes", "optometr", "eye"),
        "therapy" to listOf("therapy", "therapie", "psych"),
        "haircut" to listOf("hair", "coiffure", "barber", "barbier"),
        "beauty" to listOf("beauty", "beaute", "spa", "cosmetic", "nails"),
        "wellness" to listOf("wellness", "bien etre", "meditation", "yoga"),
        "sport" to listOf("gym", "fitness", "sport", "entrainement", "workout"),
        "health" to listOf("health", "sante"),
        "movie" to listOf("movie", "cinema", "film"),
        "games" to listOf("game", "jeu", "jeux", "gaming"),
        "music" to listOf("music", "musique", "concert"),
        "party" to listOf("party", "fete", "celebration"),
        "theatre" to listOf("theatre", "theater", "show", "spectacle"),
        "art" to listOf("art", "craft", "hobby", "loisir"),
        "outdoors" to listOf("outdoor", "plein air", "camping", "park"),
        "hiking" to listOf("hiking", "randonnee"),
        "pool" to listOf("pool", "piscine", "swim"),
        "casino" to listOf("casino", "lottery", "loterie", "loto"),
        "ticket" to listOf("entertainment", "divertissement", "ticket", "billet", "events"),
        "baby" to listOf("baby", "bebe", "diaper", "couche"),
        "child" to listOf("kids", "child", "enfant", "daycare", "garderie"),
        "school" to listOf("school", "ecole", "education", "tuition", "course", "cours", "university", "universite"),
        "book" to listOf("book", "livre", "reading", "lecture"),
        "family" to listOf("family", "famille"),
        "elderly" to listOf("parents", "elderly"),
        "charity" to listOf("charity", "donation", "don ", "dons", "organisme"),
        "church" to listOf("church", "eglise", "dime", "tithe"),
        "birthday" to listOf("birthday", "anniversaire"),
        "gift" to listOf("gift", "cadeau", "present"),
        "repeat" to listOf("subscription", "abonnement", "streaming"),
        "invest" to listOf("invest", "placement", "tfsa", "celi", "rrsp", "reer", "fhsa", "stocks", "etf"),
        "crypto" to listOf("crypto", "bitcoin"),
        "savings" to listOf("saving", "epargne", "emergency", "urgence"),
        "tax" to listOf("tax", "impot", "taxes"),
        "loan" to listOf("loan", "pret ", "debt", "dette"),
        "card" to listOf("credit card", "carte de credit", "interest charge"),
        "fees" to listOf("fee", "frais", "bank charge"),
        "legal" to listOf("legal", "lawyer", "avocat", "notaire", "notary"),
        "work" to listOf("salary", "salaire", "paycheque", "paycheck", "job", "work", "travail"),
        "business" to listOf("business", "entreprise", "freelance", "contract", "contrat"),
        "spark" to listOf("bonus", "side", "extra", "prime "),
        "refund" to listOf("refund", "remboursement", "rebate"),
        "sale" to listOf("sold", "vente", "resale", "marketplace"),
        "cash" to listOf("cash", "comptant", "atm", "allowance", "allocation"),
        "delivery" to listOf("shipping", "postage", "courier"),
        "mail" to listOf("mail", "poste"),
        "online" to listOf("online", "en ligne", "domain", "hosting"),
        "cloud" to listOf("cloud", "storage", "software", "logiciel", "apps"),
    )

    /** The icon [name] suggests, or null when no word of it is known. */
    fun suggest(name: String): String? {
        val n = " " + BankStatements.normalize(name) + " "
        if (n.isBlank()) return null
        return HINTS.firstOrNull { (_, words) -> words.any { " $it" in n } }?.first
    }
}
