#!/usr/bin/env python3
"""Turn one baseline run directory into `report.md`: the generated tables behind the analysis.

    python3 scripts/perf/report.py docs/perf/runs/2026-09-19
"""
import json
import sys
from pathlib import Path


def read_jsonl(path):
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text().splitlines() if l.strip()]


def us(ns):
    """Nanoseconds as a short human figure."""
    if ns is None:
        return "–"
    if ns < 1_000:
        return f"{ns} ns"
    if ns < 1_000_000:
        return f"{ns / 1000:.1f} µs"
    if ns < 1_000_000_000:
        return f"{ns / 1_000_000:.2f} ms"
    return f"{ns / 1_000_000_000:.2f} s"


def kb(b):
    if b is None:
        return "–"
    if b < 1024:
        return f"{b} B"
    if b < 1024 * 1024:
        return f"{b / 1024:.1f} KiB"
    return f"{b / 1024 / 1024:.2f} MiB"


def ir(n):
    if n is None:
        return "–"
    if n < 1_000:
        return str(n)
    if n < 1_000_000:
        return f"{n / 1000:.1f} k"
    if n < 1_000_000_000:
        return f"{n / 1_000_000:.2f} M"
    return f"{n / 1_000_000_000:.2f} G"


def outcome(row):
    if row["ok"] == row["iters"]:
        return "ok"
    codes = ", ".join(f"`{c}`" for c in row.get("codes", {}))
    return f"{row['ok']}/{row['iters']} ok, {codes}" if row["ok"] else codes or "error"


def group_of(name):
    parts = name.split(".")
    if parts[0] == "op":
        return parts[1]
    return "path"


GROUP_TITLES = {
    "bus": "bus", "app": "app", "audit": "audit", "workspace": "workspace", "project": "project", "task": "task",
    "module": "module", "notes": "notes", "mailbox": "mailbox", "session": "session", "overlap": "overlap",
    "guardrail": "guardrail", "worktree": "worktree", "git": "git", "integration": "integration", "file": "file",
    "device": "device (no Android SDK on the measuring machine: refusal paths)", "avd": "avd (same)",
    "provider": "provider", "usage": "usage", "skill": "skill", "github": "github (no gh on the measuring machine)",
    "plugin": "plugin", "notify": "notify", "settings": "settings", "dashboard": "dashboard",
    "ui": "ui (no client attached in-process: what the engine does before the UI executor)", "os": "os (same)",
    "path": "paths that are not ops",
}


def main():
    run = Path(sys.argv[1])
    env = json.loads((run / "environment.json").read_text()) if (run / "environment.json").exists() else {}
    native = read_jsonl(run / "native.jsonl")
    scale = {r["name"].split("@")[0]: r for r in read_jsonl(run / "scale10.jsonl")}
    strace = {r["name"]: r for r in read_jsonl(run / "strace.jsonl")}
    profiles = json.loads((run / "profiles.json").read_text()) if (run / "profiles.json").exists() else {}
    soak = json.loads((run / "soak.json").read_text()) if (run / "soak.json").exists() else None
    process = json.loads((run / "process.json").read_text()) if (run / "process.json").exists() else None

    out = []
    p = out.append
    p(f"# Performance baseline run {env.get('date', run.name)}")
    p("")
    p("Generated by `scripts/perf/report.py` from the JSON in this directory. The analysis that")
    p("reads these numbers is `docs/perf/BASELINE-<date>.md`; this file is the evidence.")
    p("")
    p("## Environment")
    p("")
    for k in ("date", "git_sha", "git_branch", "rustc", "profile", "kernel", "cpu", "cores", "mem_gib", "valgrind", "strace", "load_at_start", "container"):
        if k in env:
            p(f"- {k}: `{env[k]}`")
    p("")
    p("## How to read the tables")
    p("")
    p("- **p50 / p95**: wall time of one iteration of the measured region, in process, no socket unless the name says so.")
    p("- **cpu**: process CPU time per iteration (user + system, every thread). Above wall means other threads worked; below means the iteration waited.")
    p("- **allocs / bytes**: heap allocations and bytes requested per iteration, counted by a global allocator wrapper.")
    p("- **syscalls**: from a separate strace pass with fewer iterations; the count is per iteration, every thread.")
    p("- **Ir**: instructions retired per iteration under callgrind, deterministic. The breakdown is self cost by subsystem.")
    p("- **result**: size of the JSON result the op returned, which is what crosses the socket to a client.")
    p("- A row whose outcome is an error code measured that refusal path; the note beside the group says why.")
    p("")

    p("## Headline: the paths a person feels")
    p("")
    headline = [
        ("path.engine.startup", "engine start on a populated store (open, build, recover, skills)"),
        ("path.socket.connect", "a client connects and pings"),
        ("op.session.list", "session list (rerun on every session.changed)"),
        ("op.task.list", "board load"),
        ("op.session.input", "one keystroke, in process"),
        ("path.socket.keystroke", "one keystroke, through the socket"),
        ("op.session.scrollback.tail", "terminal tail read"),
        ("path.pty.time_to_first_output", "spawn to first line on screen"),
        ("op.session.create", "new session (worktree checkout)"),
        ("op.session.close", "close a running session"),
        ("path.pty.burst_1mib", "1 MiB of terminal output end to end"),
        ("op.git.status", "git status"),
        ("op.file.tree", "file tree, one level"),
        ("op.file.search", "file search, 1 500 files"),
        ("op.settings.set", "an audited mutation"),
        ("path.event.roundtrip", "mutation to event on a subscriber"),
    ]
    by_name = {r["name"]: r for r in native}
    p("| path | what | p50 | p95 | cpu | allocs | Ir |")
    p("|---|---|---:|---:|---:|---:|---:|")
    for name, what in headline:
        r = by_name.get(name)
        if not r:
            continue
        pr = profiles.get(name, {})
        p(f"| `{name}` | {what} | {us(r['wall_ns']['p50'])} | {us(r['wall_ns']['p95'])} | {us(r['cpu_ns_per_iter'])} | {r['allocs_per_iter']} | {ir(pr.get('ir_per_iter'))} |")
    p("")

    groups = {}
    for r in native:
        groups.setdefault(group_of(r["name"]), []).append(r)
    p("## Every scenario")
    p("")
    for g, rows in groups.items():
        p(f"### {GROUP_TITLES.get(g, g)}")
        p("")
        p("| scenario | p50 | p95 | cpu | allocs | bytes | syscalls | result | Ir | outcome |")
        p("|---|---:|---:|---:|---:|---:|---:|---:|---:|---|")
        for r in rows:
            st = strace.get(r["name"], {}).get("strace") or {}
            sc = round(st["total"] / strace[r["name"]]["iters"], 1) if st and strace[r["name"]]["iters"] else "–"
            pr = profiles.get(r["name"], {})
            p(f"| `{r['name']}` | {us(r['wall_ns']['p50'])} | {us(r['wall_ns']['p95'])} | {us(r['cpu_ns_per_iter'])} | {r['allocs_per_iter']} | {kb(r['alloc_bytes_per_iter'])} | {sc} | {kb(r['result_bytes'])} | {ir(pr.get('ir_per_iter'))} | {outcome(r)} |")
        p("")

    if scale:
        p("## Ten times the rows")
        p("")
        p("The same list queries against a store with 400 tasks, 100 notes, 100 messages and 500 extra audit rows instead of 40, 10, 10, 50. A ratio near 10 is linear in the rows; well below is a fixed cost; above is worse than linear.")
        p("")
        p("| scenario | p50 ×1 | p50 ×10 | ratio | allocs ×1 | allocs ×10 | result ×10 |")
        p("|---|---:|---:|---:|---:|---:|---:|")
        for name, r10 in scale.items():
            r1 = by_name.get(name)
            if not r1:
                continue
            ratio = r10["wall_ns"]["p50"] / max(r1["wall_ns"]["p50"], 1)
            p(f"| `{name}` | {us(r1['wall_ns']['p50'])} | {us(r10['wall_ns']['p50'])} | {ratio:.1f}× | {r1['allocs_per_iter']} | {r10['allocs_per_iter']} | {kb(r10['result_bytes'])} |")
        p("")

    if profiles:
        p("## Where the instructions go")
        p("")
        p("Per scenario, under callgrind: instructions per iteration, self cost by subsystem (every bucket at or above 0.5 %), the inclusive share of a few known entry points, and the Relay functions with the largest inclusive cost below the pipeline. Inclusive figures overlap; they answer \"how much of this op is X\".")
        p("")
        for name, pr in profiles.items():
            r = by_name.get(name)
            p(f"### `{name}` — {ir(pr['ir_per_iter'])} instructions/iteration" + (f", {us(r['wall_ns']['p50'])} native p50" if r else ""))
            p("")
            p("- by subsystem: " + " · ".join(f"{k} **{v}%**" for k, v in pr["buckets"].items()))
            if pr.get("markers"):
                p("- inclusive: " + " · ".join(f"{k} {v}%" for k, v in sorted(pr["markers"].items(), key=lambda kv: -kv[1])))
            if pr.get("top_inclusive_relay"):
                p("- Relay functions: " + " · ".join(f"`{t['fn'].split('::')[-1] if '::' in t['fn'] else t['fn']}` {t['pct']}%" for t in pr["top_inclusive_relay"][:6]))
            if pr.get("top_self"):
                p("- hottest self: " + " · ".join(f"`{t['fn'][:60]}` {t['pct']}%" for t in pr["top_self"][:5]))
            p("")

    if soak:
        p("## Memory over 20 000 mixed operations")
        p("")
        p("Ten ops per round (session.list, task.list, a keystroke, a scrollback tail, task.update, notes.list, settings.set, mailbox.list, app.status, git.status). Live heap is what the allocator wrapper has handed out and not been given back; RSS is the process; store is the SQLite file.")
        p("")
        p("| ops | live heap | RSS | store | threads |")
        p("|---:|---:|---:|---:|---:|")
        for s in soak["samples"]:
            p(f"| {s['ops']} | {s['live_heap_kb'] / 1024:.1f} MiB | {s['rss_kb'] / 1024:.1f} MiB | {s['store_kb'] / 1024:.1f} MiB | {s['threads']} |")
        p("")

    if process:
        p("## The engine process from the outside")
        p("")
        p(f"A real `relay serve` (dev profile) with six fake sessions, sampled from `/proc` over {process['window_seconds']} s windows. Wakeups are voluntary context switches summed over every thread; CPU is at kernel tick resolution.")
        p("")
        p(f"- startup on a fresh store: **{process['startup_s_fresh_store']} s** to the first answered ping; RSS {process['rss_mb_fresh']} MiB fresh, {process['rss_mb_six_sessions']} MiB with six sessions")
        rs = process.get("restart_s", {})
        p(f"- restart with six live sessions to reap: **{rs.get('with_six_live_sessions')} s**; clean restarts: {', '.join(str(x) + ' s' for x in rs.get('clean', []))}")
        p("")
        p("| phase | CPU % | CPU ms in window | wakeups/s | preemptions/s | RSS | threads |")
        p("|---|---:|---:|---:|---:|---:|---:|")
        for name, ph in process["phases"].items():
            if "cpu_percent" not in ph:
                continue
            p(f"| {name.replace('_', ' ')} | {ph['cpu_percent']} | {ph['cpu_ms_total']} | {ph['wakeups_per_s']} | {ph['preemptions_per_s']} | {ph['rss_mb']} MiB | {ph['threads']} |")
        b = process["phases"].get("burst_50k_lines_attached")
        if b:
            p("")
            p(f"- burst of 50 000 lines (4.9 MB) to an attached client: stream quiet after **{b['seconds_until_stream_quiet']} s** (includes a 1 s silence wait), {b['engine_cpu_ms']} ms engine CPU, {b['frames']} frames, {kb(b['wire_bytes_received'])} on the wire carrying {kb(b['payload_bytes_received'])} of the {kb(b['payload_bytes'])} payload")
        if process.get("cli"):
            p("")
            p("| CLI call | min | p50 | max |")
            p("|---|---:|---:|---:|")
            for k, v in process["cli"].items():
                p(f"| `relay {k.replace('_', ' ')}` | {v['min_ms']} ms | {v['p50_ms']} ms | {v['max_ms']} ms |")
        p("")

    (run / "report.md").write_text("\n".join(out) + "\n")
    print(run / "report.md")


if __name__ == "__main__":
    main()
